version: '3'
services:
    backend:
      build:
          context: ./
          dockerfile: dockerize/backend/Dockerfile
      ports:
        - 8050:8000
      volumes:
        - ./backend:/backend

    frontend:
      build:
          context: ./
          dockerfile: dockerize/frontend/Dockerfile
      ports:
        - 9090:8081
      volumes:
        - ./frontend:/frontend
      working_dir: /frontend

    mysql:
        image: mysql:5.7.22
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "4306:3306"
        volumes:
            - ./etc/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: thefthing
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
